services:
  mongo: 
    image: mongo
    container_name: mongo_Emilio
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~E:\2DAM\Diseño de interfaces\1 evaluacion\ReapasoRecuperacion\volumenesDB
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express_Emilio
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

